spring.datasource.url=jdbc:postgresql://localhost:5432/traffic_analyzer
spring.datasource.username=traffic_app
spring.datasource.password=Spar34App
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
