spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/traffic_analyzer}
spring.datasource.username=${DB_USER:traffic_app}
spring.datasource.password=${DB_PASSWORD:Spar34App}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect